CREATE TABLE USERS(NAME TEXT UNIQUE, PASSWORD TEXT, BALANCE FLOAT);
CREATE TABLE TRADE_IDS(ID TEXT UNIQUE, COST FLOAT, OWNER_NAME TEXT)
CREATE TABLE SUBSCRIPTIONS(NAME TEXT UNIQUE, TRADEPACK INTEGER, NOADS INTEGER)
CREATE TABLE OPERATIONS(TOUSER TEXT, FROMUSER TEXT, VALUE FLOAT, COMMENT TEXT);

CREATE TABLE ADS(NAME TEXT, DESC TEXT, COST FLOAT)

ALTER TABLE USERS ADD TRADEPACK BOOLEAN
ALTER TABLE USERS ADD NOADS BOOLEAN
ALTER TABLE OPERATIONS ADD OPDATE DATETIME

CREATE TABLE NEW_OPERATIONS(TOUSER TEXT, FROMUSER TEXT, VALUE FLOAT, COMMENT TEXT, OPDATE DATETIME);